- name: configure web server
  hosts: all
  become: true
  tasks:
    - name: update cache
      dnf:
        update_cache: yes

    - name: install packages
      dnf:
        name: "{{ item }}"
        state: present
      loop: 
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - docker
        - git

    - name: add docker repo
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    
    - name:  add docker gpg key
      rpm_key:
        key: https://download.docker.com/linux/centos/gpg
        state: present

    - name: update cache
      dnf:
        update_cache: yes
    
    - name: start and enable docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: create docker group
      group:
        name: docker
        state: present
    
    - name: add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
    
    - name: make new directory to copy the app 
      file:
        path: /home/ec2-user/app
        state: directory
        mode: 0755

    - name: clone the app
      git:
        repo: https://github.com/Adeayo10/NISA.git
        dest: /home/ec2-user/app

    - name: stop exisitng docker container
      shell: |
        docker ps --filter "publish=80" -q | xargs -r docker stop
        docker ps --filter "publish=80" -q | xargs -r docker rm

    - name: build the docker image
      command: docker build -t nodeapp /home/ec2-user/app/node

    - name: run the docker container
      command: docker run -d --name nodeapp -p 80:3000 nodeapp
