name: Build and Deploy to doceerized contain on AWS EC2 on changes to master branch

on:
    push:
        branches:
            - master
        paths:
            - "node/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./node
          file: ./node/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/doceerized:latest

      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SSH_HOST }}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/doceerized:latest
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker run -d -p 80:3000 ${{ vars.DOCKERHUB_USERNAME }}/doceerized:latest




