name: Build and Deploy to doceerized contain on AWS EC2 on changes to master branch

on:
  push:
    branches:
      - main
    paths:
      - 'node/**'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
    
            - name: set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            
            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ vars.DOCKERHUB_USERNAME }}/doceerized:latest

            - name: SSH to AWS EC2
              uses: webfactory/ssh-agent@v0.5.3
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                

            - name: Deploy to AWS EC2
              run: |
                ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USERNAME }}@${{ secrets.AWS_SSH_HOST }} 'docker pull ${{ vars.DOCKERHUB_USERNAME }}/doceerized:latest && docker run -d -p 80:80 ${{ vars.DOCKERHUB_USERNAME }}/doceerized:latest'

   
            
                    



    

   